### ISSUE TITLE
sql fields

### ISSUE THREAD

**Issue by cerhardt** [PSU-REDCap/redcap-support-ticketing-system#1]
The two sql statements in the fields "sql_assignment" and "sql_closed" are missing in the project XML. Can you please provide them separately?

Thank you, Christian

**Comment by meb54** [comment]
The sql_calc instrument is strictly for helping to figure out stats and was created to be used on a project dashboard. It would be better to use statistical software to generate the statistics but at the time we created this project we were supposed to use only redcap functionality. This instrument does not automatically populate. To populate the values you need to open and save the instrument, use the api, data quality rule H, or whatever your favorite method of triggering calculations is. 

Here are the requested queries:
SELECT 
	b.value as month, 
	ROUND(AVG(a.value), 2) as value 
	FROM redcap_data a 
LEFT JOIN redcap_data b on a.project_id = b.project_id AND a.record = b.record 
WHERE a.project_id = [project-id] 
	AND a.field_name = 'assignment_days' 
	AND b.field_name = 'month_for_reports' 
GROUP BY month

SELECT 
	b.value as month, 
	ROUND(AVG(a.value), 2) as value 
FROM redcap_data a 
LEFT JOIN redcap_data b on a.project_id = b.project_id AND a.record = b.record 
WHERE a.project_id = [project-id] 
	AND a.field_name = 'closed_days' 
	AND b.field_name = 'month_for_reports' 
GROUP BY month

**Comment by cerhardt** [comment]
thank you very much!
